# Generated by Django 6.0.7 on 2026-07-08 05:18

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_date',
                    models.DateField(
                        default=datetime.date.today, verbose_name='дата'
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.01')
                            )
                        ],
                        verbose_name='сумма',
                    ),
                ),
                (
                    'comment',
                    models.TextField(blank=True, verbose_name='комментарий'),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='records',
                        to='cashflow.category',
                        verbose_name='категория',
                    ),
                ),
                (
                    'status',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='records',
                        to='cashflow.status',
                        verbose_name='статус',
                    ),
                ),
                (
                    'subcategory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='records',
                        to='cashflow.subcategory',
                        verbose_name='подкатегория',
                    ),
                ),
                (
                    'type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='records',
                        to='cashflow.type',
                        verbose_name='тип',
                    ),
                ),
            ],
            options={
                'verbose_name': 'запись ДДС',
                'verbose_name_plural': 'записи ДДС',
                'ordering': ['-created_date', '-id'],
            },
        ),
    ]
